### ISSUE TITLE
Receive() should return the message for further processing

### ISSUE THREAD

**Issue by apognu** [nb-titan/gcm#16]
Hi,

Currently, the message ID is generated when the message is sent, and we have no way of getting it before it gets across the wire.

I want to track my message delivery status and need a way to match an ACK to a sent message. Storing the message ID when it is crafted would allow me to do just that.

I can develop it myself and make a PR if necessary.

Regards,

**Comment by apognu** [comment]
Oh, my bad, the message struct is modified with the generated ID. Should have read the code more carefully...

Sorry about that.

**Comment by apognu** [comment]
Well, actually, the problem just shifted to somewhere else, ACK messages from CCS server are ignored by Receive() and therefore cannot be handled.

**Comment by soygul** [comment]
Ok clarified that in the docs: https://github.com/nb-titan/gcm/commit/2735ed87396fbafc1a743d0ec64d41f40f1ece54
